# distcc_hosts:
# portage_overlay:
# pkgcache_path:
# kerncache_path:
stage4/use:
stage4/packages: @ceph
# stage4/fsscript:
# stage4/splash_theme:
# stage4/gk_mainargs:
# stage4/linuxrc:
# stage4/motd:
# stage4/modblacklist:
# stage4/rcadd:
# stage4/rcdel:
# stage4/root_overlay:
# stage4/xinitrc:
# stage4/users:
boot/kernel: gentoo
boot/kernel/gentoo/sources: gentoo-sources
boot/kernel/gentoo/config: /root/kernel-config/kernel-config-x86_64-latest-gentoo
# boot/kernel/gentoo/gk_kernargs:
# boot/kernel/gentoo/use:
# boot/kernel/gentoo/extraversion:
# boot/kernel/gentoo/packages:
# stage4/unmerge:
stage4/empty: /usr/src
# stage4/rm:
